# Generated by Django 4.2 on 2025-04-13 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import matrix.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_remove_company_employees_alter_company_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, verbose_name='Оценка')),
                ('evaluation_number', models.PositiveSmallIntegerField(verbose_name='Числовая оценка')),
            ],
            options={
                'verbose_name': 'Шаблон оценки навыка',
                'verbose_name_plural': 'Шаблон оценок навыков',
            },
        ),
        migrations.CreateModel(
            name='GradeSkillMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gradeskillmatrix', to='matrix.gradeskill', verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_application', models.CharField(max_length=11, verbose_name='Область')),
                ('skill', models.CharField(max_length=150, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['area_of_application'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temmplate_matrix', to=settings.AUTH_USER_MODEL, verbose_name='Автор шаблона')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temmplate_matrix', to='companies.company', verbose_name='Компания')),
                ('skills', models.ManyToManyField(related_name='template_matrix', to='matrix.skill', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Шаблон матрицы',
                'verbose_name_plural': 'Шаблоны матриц',
            },
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Назначенная матрица', max_length=20, verbose_name='Наименование')),
                ('status', models.CharField(choices=[('Новая', 'Новая'), ('В процессе', 'В процессе'), ('Завершена', 'Завершена'), ('Просрочена', 'Просрочена')], default='Новая', max_length=10, validators=[matrix.validators.validation_check_status], verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_update_status', models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение статуса')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('skills', models.ManyToManyField(related_name='matrix', through='matrix.GradeSkillMatrix', to='matrix.skill')),
                ('template_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to='matrix.templatematrix', verbose_name='Шаблон на основании которого создана матрица')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Матрица',
                'verbose_name_plural': 'Матрицы',
            },
        ),
        migrations.AddField(
            model_name='gradeskillmatrix',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradeskillmatrix', to='matrix.matrix', verbose_name='Матрица'),
        ),
        migrations.AddField(
            model_name='gradeskillmatrix',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradeskillmatrix', to='matrix.skill', verbose_name='Навык'),
        ),
    ]
