# Generated by Django 4.2 on 2024-12-09 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Шаблон оценки навыка',
                'verbose_name_plural': 'Шаблон оценок навыков',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_application', models.CharField(max_length=11, verbose_name='Область')),
                ('skill', models.CharField(max_length=150, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['area_of_application'],
            },
        ),
        migrations.CreateModel(
            name='GradeCompetenceJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность сотрудника')),
                ('min_grade', models.CharField(max_length=50, verbose_name='Минимальная оценка')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_competence', to='matrix.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Уровень навыков по должности',
                'verbose_name_plural': 'Уровень навыков по должностям',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('grade_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.gradeskill', verbose_name='Оценка')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_competence', to='matrix.skill', verbose_name='Навык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
                'ordering': ['user'],
            },
        ),
    ]
