# Generated by Django 4.2 on 2024-12-05 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_application', models.CharField(choices=[('Hard', 'Hard skill'), ('Soft', 'Soft skill'), ('Tool', 'Tool')], max_length=11, verbose_name='Область')),
                ('skill', models.CharField(max_length=150, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['area_of_application'],
            },
        ),
        migrations.CreateModel(
            name='GradeCompetenceJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность сотрудника')),
                ('min_grade', models.CharField(max_length=50, verbose_name='Минимальная оценка')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_competence', to='matrix.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Уровень навыков по должности',
                'verbose_name_plural': 'Уровень навыков по должностям',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_skill', models.CharField(choices=[('No Skills', 'No Skills'), ('Basic', 'Basic'), ('Good', 'Good'), ('Good+', 'Good+'), ('Strong', 'Strong'), ('Expert', 'Expert')], max_length=10, verbose_name='Оценка навыка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='matrix.skill', verbose_name='Навык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
                'ordering': ['user'],
            },
        ),
    ]
