# Generated by Django 4.2 on 2024-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='area_of_application',
            field=models.CharField(choices=[('Hard skill', 'Hard skill'), ('Soft skill', 'Soft skill'), ('Tool', 'Tool')], max_length=11, verbose_name='Область'),
        ),
    ]
