# Generated by Django 4.2 on 2025-04-20 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_employees_alter_company_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatematrix',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_matrix', to=settings.AUTH_USER_MODEL, verbose_name='Автор шаблона'),
        ),
        migrations.AlterField(
            model_name='templatematrix',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_matrix', to='companies.company', verbose_name='Компания'),
        ),
    ]
