# Generated by Django 4.2 on 2024-12-21 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competence',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='gradeskill',
            name='evaluation_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Числовая оценка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradecompetencejobtitle',
            name='min_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.gradeskill', verbose_name='Минимальная оценка'),
        ),
    ]
