# Generated by Django 4.2 on 2025-01-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_rename_date_competence_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Компетенция', 'verbose_name_plural': 'Компетенции'},
        ),
    ]
