# Generated by Django 4.2 on 2024-12-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_alter_skill_area_of_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='date',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='grade_skill',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='skill',
        ),
        migrations.AlterField(
            model_name='skill',
            name='area_of_application',
            field=models.CharField(max_length=11, verbose_name='Область'),
        ),
        migrations.CreateModel(
            name='SkillCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_skill', models.CharField(choices=[('No Skills', 'No Skills'), ('Basic', 'Basic'), ('Good', 'Good'), ('Good+', 'Good+'), ('Strong', 'Strong'), ('Expert', 'Expert')], max_length=10, verbose_name='Оценка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_competence', to='matrix.competence', verbose_name='Компетенция')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_competence', to='matrix.skill', verbose_name='Навык')),
            ],
        ),
        migrations.AddField(
            model_name='competence',
            name='skill',
            field=models.ManyToManyField(through='matrix.SkillCompetence', to='matrix.skill'),
        ),
    ]
