# Generated by Django 4.2 on 2025-04-25 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrix', '0002_alter_templatematrix_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
