# Generated by Django 4.2 on 2025-01-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_alter_competence_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата оценки'),
        ),
    ]
