# Generated by Django 4.2 on 2024-12-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_alter_gradeskill_evaluation_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competence',
            old_name='date',
            new_name='created_at',
        ),
    ]
