# Generated by Django 4.2 on 2025-04-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_alter_gradeskill_evaluation_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='area_of_application',
            field=models.CharField(choices=[('Hard skill', 'Hard skill'), ('Soft skill', 'Soft skill'), ('Tool', 'Tool')], max_length=11, verbose_name='Область'),
        ),
    ]
