# Generated by Django 4.2 on 2025-01-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_alter_competence_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки'),
        ),
    ]
