# Generated by Django 4.2 on 2025-03-17 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrix', '0005_alter_competence_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'verbose_name': 'Компетенция', 'verbose_name_plural': 'Компетенции'},
        ),
        migrations.RemoveField(
            model_name='competence',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='competence',
            name='user',
        ),
        migrations.AlterField(
            model_name='competence',
            name='grade_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matrix.gradeskill', verbose_name='Оценка'),
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField()),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrix.competence', verbose_name='Компетенция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
