# Generated by Django 4.2 on 2025-03-17 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0006_alter_competence_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrix',
            options={'verbose_name': 'Матрица', 'verbose_name_plural': 'Матрицы'},
        ),
        migrations.RemoveField(
            model_name='matrix',
            name='competence',
        ),
        migrations.AddField(
            model_name='competence',
            name='matrix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='matrix.matrix'),
            preserve_default=False,
        ),
    ]
