# Generated by Django 4.2 on 2025-03-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0007_alter_matrix_options_remove_matrix_competence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование'),
        ),
    ]
