# Generated by Django 4.2 on 2025-03-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0008_alter_matrix_completed_at_alter_matrix_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='status',
            field=models.CharField(default='Новая', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='name',
            field=models.CharField(default='Назначенная матрица', max_length=20, verbose_name='Наименование'),
        ),
    ]
