# Generated by Django 4.2 on 2025-03-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0009_matrix_status_alter_matrix_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='matrix.matrix'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Завершена', 'Завершена'), ('Просрочена', 'Просрочена')], default='Новая', max_length=10, verbose_name='Статус'),
        ),
    ]
