# Generated by Django 4.2 on 2025-03-29 09:57

from django.db import migrations, models
import django.db.models.deletion
import matrix.validators


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0010_alter_competence_matrix_alter_matrix_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='grade_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matrix.gradeskill', verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Завершена', 'Завершена'), ('Просрочена', 'Просрочена')], default='Новая', max_length=10, validators=[matrix.validators.validation_check_status], verbose_name='Статус'),
        ),
    ]
