# Generated by Django 4.2 on 2025-04-12 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.AlterField(
            model_name='company',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыта от'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана от'),
        ),
        migrations.AlterField(
            model_name='company',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_company', to=settings.AUTH_USER_MODEL, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='OldCompanyEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, verbose_name='Должность которая была в этой компании')),
                ('date_of_employment', models.DateField(null=True, verbose_name='Дата трудоустройства')),
                ('date_of_dismissal', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_company', to='companies.company', verbose_name='Старая компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_old_company', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Старая компания сотрудника',
                'verbose_name_plural': 'Старые компании сотрудников',
            },
        ),
    ]
