# Generated by Django 4.2 on 2025-04-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_employees_alter_company_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
