# Generated by Django 4.2 on 2025-03-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
