# Generated by Django 4.2 on 2025-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_closed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='director',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
