# Generated by Django 4.2 on 2025-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_director_remove_company_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыта от'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана от'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
