# Generated by Django 4.2 on 2025-04-05 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0006_alter_company_closed_at_alter_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='director',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='director_company', to=settings.AUTH_USER_MODEL, verbose_name='Директор'),
            preserve_default=False,
        ),
    ]
