# Generated by Django 4.2 on 2025-04-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobdepartment_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobgroup',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='jobmanagement',
            name='children',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.DeleteModel(
            name='JobDepartment',
        ),
        migrations.DeleteModel(
            name='JobGroup',
        ),
        migrations.DeleteModel(
            name='JobManagement',
        ),
    ]
