# Generated by Django 4.2 on 2025-01-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_department_remove_user_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdepartment',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='jobgroup',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='jobmanagement',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jobdepartment', verbose_name='Департамент'),
        ),
    ]
