# Generated by Django 4.2 on 2025-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_jobgroup_parent_remove_jobmanagement_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
    ]
