# Generated by Django 4.2 on 2025-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_delete_jobdepartment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdepartment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Отметить если удален', verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Отметить если удален', verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='jobmanagement',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Отметить если удален', verbose_name='Удален'),
        ),
    ]
