# Generated by Django 4.2 on 2024-11-28 16:16

from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_personnel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdepartment',
            name='children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jobgroup', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='jobdepartment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jobmanagement', verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='jobgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jobdepartment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personnel_number',
            field=models.CharField(max_length=8, null=True, unique=True, validators=[users.validators.validation_min_length_personnal_number], verbose_name='Табельный номер'),
        ),
    ]
