# Generated by Django 4.2 on 2025-03-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_refreshtoken_refresh_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
