# Generated by Django 4.2 on 2025-03-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_director',
            field=models.BooleanField(default=False, help_text='Проставить если сотрудник является директором компании'),
        ),
    ]
