# Generated by Django 4.2 on 2025-03-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_director',
            field=models.BooleanField(default=False, help_text='Проставить если сотрудник является директором компании', verbose_name='Статус директора'),
        ),
    ]
