# Generated by Django 4.2 on 2025-04-05 09:12

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_dismissal',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 9, 12, 25, 237117, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_employment',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
