# Generated by Django 4.2 on 2025-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_date_of_dismissal_user_date_of_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_dismissal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_employment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
