# Generated by Django 4.2 on 2025-04-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_date_of_dismissal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_dismissal',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата трудоустройства'),
        ),
    ]
